ci: Add snitch/occamy related tests and try to fix pulp ci tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -86,6 +86,21 @@ tc-pulp:
         $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert tc-pulp
       fi
 
+tc-snitch:
+  stage: build1
+  needs: ["pre-downstream-checkout"]
+  script:
+    - >
+      if ! $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh lookup tc-snitch; then
+        export CXX=/usr/pack/gcc-9.2.0-af/linux-x64/bin/g++ # LLVM 12 needs 5.1+
+        export CC=/usr/pack/gcc-9.2.0-af/linux-x64/bin/gcc  # LLVM 12 needs 5.1+
+        make tc-snitch
+        unset CXX # Cleanup after LLVM 12 build
+        unset CC  # Cleanup after LLVM 12 build
+        chmod -R u+w $HERO_INSTALL
+        $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert tc-snitch
+      fi
+
 tc-har-olinux:
   stage: build1
   needs: ["pre-downstream-checkout"]
@@ -162,6 +177,22 @@ sdk-pulp-and-sdk-hrv:
     - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-hrv-olinux
     - chmod -R u-w $HERO_INSTALL
     - make sdk-pulp-hrv
+    - make sdk-hrv
+    - chmod -R u+w $HERO_INSTALL
+    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert sdk-pulp-and-sdk-hrv
+
+sdk-snitch-and-sdk-hrv:
+  stage: build2
+  needs: ["tc-snitch", "tc-hrv-olinux"]
+  script:
+    - >
+      if $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh lookup sdk-snitch-and-sdk-hrv; then
+        exit 0
+      fi
+    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-snitch
+    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-hrv-olinux
+    - chmod -R u-w $HERO_INSTALL
+    - make sdk-snitch
     - make sdk-hrv
     - chmod -R u+w $HERO_INSTALL
     - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert sdk-pulp-and-sdk-hrv
