modify hc-omp-pass to generic omp pass script

diff --git a/toolchain/hc-omp-pass b/toolchain/hc-omp-pass
--- a/toolchain/hc-omp-pass
+++ b/toolchain/hc-omp-pass
@@ -3,7 +3,7 @@
 # ======================== CONFIGURATION OPTIONS =========================== #
 
 # HERCULES passes build directory.
-PASSROOT="$RISCV/lib/hercules/"
+PASSROOT="$RISCV/lib/hercules"
 
 # LLVM bin directory (empty for standard PATH).
 # Note: Must end with slash character ("/") unless empty.
@@ -16,8 +16,18 @@ CFLAGS=""
 
 # Ensure that a file name was given as argument.
 if [ -z "$1" ]; then
-  echo "Provide IR file as arg 1!"
-  exit
+  echo "Fatal error: Provide IR file as arg 1!"
+  exit 1
+fi
+
+if [ -z "$2" ]; then
+  echo "Fatal error: Provide pass library name as arg 2!"
+  exit 1
+fi
+
+if [ -z "$3" ]; then
+  echo "Fatal error: Provide pass name as arg 3!"
+  exit 1
 fi
 
 # ========================= EXECUTION PARAMETERS =========================== #
@@ -25,13 +35,13 @@ fi
 BASENAME=$(basename "$1" .ll)
 
 # Path to the passes, based on provided root directory.
-PASS_OMP_KERNEL_WRAPPER_PATH="$PASSROOT/libOmpKernelWrapper.so"
+PASS_OMP_PATH="$PASSROOT/lib$2.so"
 
 # LLVM pass names.
-PASS_OMP_KERNEL_WRAPPER_NAME="-HERCULES-omp-kernel-wrapper"
+PASS_OMP_NAME="-$3"
 
 # Passes to run before each HERCULES pass.
-PASS_OMP_KERNEL_WRAPPER_PREREQ=""
+PASS_OMP_PREREQ=""
 
 # Passes to run at the very end.
 FINAL_OPTIMIZATIONS="-dce -gvn -instcombine -mergefunc -always-inline -simplifycfg -instcombine -elim-avail-extern -branch-prob -loop-unroll -globaldce -constmerge -always-inline"
@@ -39,11 +49,11 @@ FINAL_OPTIMIZATIONS="-dce -gvn -instcombine -mergefunc -always-inline -simplifyc
 # =============================== EXECUTION ================================ #
 
 ${LLVM_BIN_DIR}opt "$BASENAME.ll" \
--load="$PASS_OMP_KERNEL_WRAPPER_PATH"   $PASS_OMP_KERNEL_WRAPPER_PREREQ   $PASS_OMP_KERNEL_WRAPPER_NAME \
+-load="$PASS_OMP_PATH"   $PASS_OMP_PREREQ   $PASS_OMP_NAME \
 $FINAL_OPTIMIZATIONS -o "$BASENAME.OMP.ll" -S
 
 # Check that the passes were successful before continuing.
 if [ $? -ne 0 ]; then
   echo "Application of passes to $BASENAME failed, stopping here."
-  exit
+  exit 1
 fi
